version: '3'

services:

  redis:
    container_name: redis
    image: redis:5.0.5
    hostname: localhost
    network_mode: bridge
    volumes:
      - ./redis:/var/lib/redis
    ports:
      - 6379:6379/tcp