version: '3.1'

services:

  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    volumes:
      - ./elasticsearch:/var/lib/elasticsearch
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    volumes:
      - ./kibana:/var/lib/kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    
volumes:
  elasticsearch-data:
